### PR TITLE
Added support for sensors

### PR DESCRIPTION
**Pull request by juliancheal**
Sensors include: switches, presance and tempreture sensors.

### CODE REVIEW

**Comment by juliancheal** [comment]
Hi @soffes I'm not sure if you are supporting this repository any more. No worries if not, let me know and I will merge this PR into a fork. :)

**Comment by soffes** [comment]
@juliancheal I will try to take a look shortly! Thanks for your effort on this!

**Comment by soffes** [comment]
@juliancheal where can you buy those sensors? Haven't seen them before.

**Comment by juliancheal** [comment]
There is the [dimmer switch](https://www.amazon.com/Philips-473371-Dimmer-Installation-Free-Exclusive/dp/B076MGKTGS/) and a [motion sensor](https://www.amazon.com/Philips-Motion-Sensor-Installation-Free-Exclusive/dp/B01KJYSOGI/)

On the Hue API site they have https://developers.meethue.com/documentation/sensors-api & https://developers.meethue.com/documentation/supported-sensors

**Comment by juliancheal** [comment]
```
{
  "1"=>
  {
    "state"=>{
      "daylight"=>nil, "lastupdated"=>"none"
    },
    "config"=>{
      "on"=>true, "configured"=>false, "sunriseoffset"=>30, "sunsetoffset"=>-30
    },
    "name"=>"Daylight", "type"=>"Daylight", "modelid"=>"PHDL00",
    "manufacturername"=>"Philips", "swversion"=>"1.0"
  },

  "2"=>{
    "state"=>{
      "buttonevent"=>nil, "lastupdated"=>"none"
    },
    "swupdate"=>{
      "state"=>"noupdates", "lastinstall"=>nil
    },
    "config"=>{
      "on"=>true, "battery"=>100, "reachable"=>true, "pending"=>[]
    },
    "name"=>"", "type"=>"ZLLSwitch", "modelid"=>"RWL021",
    "manufacturername"=>"Philips", "swversion"=>"5.45.1.17846",
    "uniqueid"=>""
  },

  "3"=>{
    "state"=>{
      "buttonevent"=>1002, "lastupdated"=>"2017-12-13T21:12:45"
    },
    "swupdate"=>{
      "state"=>"noupdates", "lastinstall"=>nil
    },
    "config"=>{
      "on"=>true, "battery"=>100, "reachable"=>true, "pending"=>[]
    },
    "name"=>"", "type"=>"ZLLSwitch", "modelid"=>"RWL021",
    "manufacturername"=>"Philips", "swversion"=>"5.45.1.17846",
    "uniqueid"=>""
  }
}
```

I've got two Dimmer switches. I've removed the `name` and `uniqueid`. The `daylight` is new to me, but from the docs looks like it's from the `hub` if you set your `lat` `long` it gives you the sunrise and sunset times, or something like that.

**Pull request closed without merging**
